kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-health-analyzer-console
  namespace: openshift-cluster-health-analyzer
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.observability-thanos-query-user: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"cluster-health-console"}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-health-analyzer-console
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-console
    namespace: openshift-cluster-health-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view
