# creates service account with permissions to access prometheus metrics
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cluster-health-analyzer-thanos-querier
  namespace: openshift-cluster-health-analyzer
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-health-analyzer-thanos-querier
subjects:
  - kind: ServiceAccount
    name: cluster-health-analyzer-thanos-querier
    namespace: openshift-cluster-health-analyzer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-monitoring-view